sudo: required
dist: trusty

language: c
compiler: gcc

before_install:
- sudo apt-get -qq update
- sudo apt-get install -y libsdl2-dev check
before_script: ./bootstrap
script: "./configure && make && make check"