language: c
compiler: gcc
install:
    - wget http://libsdl.org/release/SDL2-2.0.3.tar.gz -O - | tar xz
    - cd SDL2-2.0.3 && ./configure && make -j && sudo make install && cd ..
before_script: ./bootstrap
script: "./configure && make"
