# TODO: Migrate to container based builds

sudo: required
dist: trusty
branches:
    only:
        - master
        - devel

language: c
compiler: gcc

before_install:
- sudo apt-get -qq update
- sudo apt-get install -y libsdl2-dev check
- pip install --user cpp-coveralls
before_script: ./bootstrap
script: "./configure --enable-gcov && make && make check"
after_success:
- coveralls --exclude tests --gcov-options '\-lp'
after_failure: "cat tests/test-suite.log"
